### ISSUE TITLE
Different port for MySQL?

### ISSUE THREAD

**Issue by kjtanaka** [PASApipeline/PASApipeline#118]
Hello,

I'd like to use a different port in the MySQL server setting -- other than the default 3306. I looked through the pasa.CONFIG.template, but cannot find the port setting. 

Is it possible? And how can I set it?

Thanks a lot,

**Comment by brianjohnhaas** [comment]
Hi,

I think you can set this in the mysql connection string in the
pasa_conf/conf.txt file.  You'll find the line:

MYSQLSERVER=localhost

in the default configuration.  I think you can set it to server:port

If that doesn't work, then it'll probably require hacking the mysql
connection code, which wouldn't be terribly difficult, but less than
ideal.  Happy to provide pointers there if needed.

~b


On Wed, Oct 2, 2019 at 8:46 PM Koji Tanaka <notifications@github.com> wrote:
>
> Hello,
>
> I'd like to use a different port in the MySQL server setting -- other
than the default 3306. I looked through the pasa.CONFIG.template, but
cannot find the port setting.
>
> Is it possible? And how can I set it?
>
> Thanks a lot,
> Koji
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas

**Comment by kjtanaka** [comment]
Thanks @brianjohnhaas !
