### ISSUE TITLE
Can PAS add the information of isoforms from the ISO-seq data?

### ISSUE THREAD

**Issue by Huangyizhong** [PASApipeline/PASApipeline#182]
Hi, Dear.
    I have used the PASA software to annotate the genome and I have some qusetions. Sorry to disturb you!
First,  I have lots of Iso-seq data to obtain the infomation of isoforms, how should I add it into the final gff files to get the full annotation files? Will the PASA do it ?
Second,  I obtained the compreh_init_build.gff3, which used as transcripts_alignments,gff file to add into the ECM model. I want to load it into the IGV to check the annotation of EVM files. But failed, would you please give some suggestions? The gff3 file wil be attached below.
Thanks so much 
Sincerely 
Yizhong Huang 
[compreh_init_build.gff3.gz](https://github.com/PASApipeline/PASApipeline/files/6344746/compreh_init_build.gff3.gz)

**Comment by brianjohnhaas** [comment]
Hi,

For the first question about using iso-seq to obtain isoforms, if you have near perfect alignments (ie. CCS reads or hifi reads), then PASA should work here. Just provide the sequences as a transcripts.fasta input file and run PASA.  Include the --TRANSDECODER option if you want it to automatically annotate likely full-length coding sequences - which is essential if you're doing a de novo annotation of a genome for which you don't have already existing gene structure annotations to update.

For the 2nd question, if you convert the gff3 file to bed format, it usually works better for viewing in IGV:

I ran this script included in the pasa software:   
pasapipeline/misc_utilities/pasa_alignment_gff3_to_bed.pl compreh_init_build.gff3  > compreh_init_build.bed

and the bed file is attached here.
[compreh_init_build.bed.gz](https://github.com/PASApipeline/PASApipeline/files/6358437/compreh_init_build.bed.gz)

IGV might require that you sort it by coordinate and maybe tabix index it, but let's see if it works as is first.

best,

~brian
