### ISSUE TITLE
Error while installing cdbtools bundled in PASA

### ISSUE THREAD

**Issue by kumarsaurabh20** [PASApipeline/PASApipeline#19]
Hi, I have just downloaded the latest version of pasa and tried installing. I get an error at cdbtools installation. Here is the log:

```
ks575@minerva:~/software/Annotation/PASA/PASApipeline-2.0.2$ make all
if [ ! -d bin ]; then mkdir bin; fi
cd pasa_cpp && make && cp pasa ../bin/.
make[1]: Entering directory `/home2/ISAD/ks575/software/Annotation_Pipeline/PASA/PASApipeline-2.0.2/pasa_cpp'
g++ -O3  -c alignment_segment.cpp -o alignment_segment.o
g++ -O3  -c cdna_alignment.cpp -o cdna_alignment.o
g++ -O3  -c common_subs.cpp -o common_subs.o
g++ -O3  -c cdna_alignment_assembler.cpp -o cdna_alignment_assembler.o
g++ -O3  -c Lobject.cpp -o Lobject.o
g++ -O3  -c stringFuncts.cpp -o stringFuncts.o
g++ -O3  -c pasa.cpp -o pasa.o
g++ -O3  -c argProcessor.cpp -o argProcessor.o
g++ -o ./pasa alignment_segment.o cdna_alignment.o common_subs.o  cdna_alignment_assembler.o Lobject.o stringFuncts.o pasa.o argProcessor.o
make[1]: Leaving directory `/home2/ISAD/ks575/software/Annotation_Pipeline/PASA/PASApipeline-2.0.2/pasa_cpp'
cd slclust && make && cp src/slclust ../bin/.
make[1]: Entering directory `/home2/ISAD/ks575/software/Annotation_Pipeline/PASA/PASApipeline-2.0.2/slclust'
X=`pwd`; \
        for i in src; \
        do echo '<<<' $i '>>>'; cd $X/$i; make all; done
<<< src >>>
make[2]: Entering directory `/home2/ISAD/ks575/software/Annotation_Pipeline/PASA/PASApipeline-2.0.2/slclust/src'
g++ -I../include -Wall  -c slcluster.cpp
g++ -I../include -Wall  -c graph.cpp
g++ -I../include -Wall  -c graphnode.cpp
g++ -I../include -Wall  -c cmd_line_opts.cpp
g++ -I../include -Wall  slcluster.o graph.o graphnode.o cmd_line_opts.o  -o slclust
chmod 755 slclust
make[2]: Leaving directory `/home2/ISAD/ks575/software/Annotation_Pipeline/PASA/PASApipeline-2.0.2/slclust/src'
make[1]: Leaving directory `/home2/ISAD/ks575/software/Annotation_Pipeline/PASA/PASApipeline-2.0.2/slclust'
cd cdbtools/cdbfasta && make && cp cdbfasta ../../bin/. && cp cdbyank ../../bin/.
make[1]: Entering directory `/home2/ISAD/ks575/software/Annotation_Pipeline/PASA/PASApipeline-2.0.2/cdbtools/cdbfasta'
Makefile:42: *** multiple target patterns. Stop.
make[1]: Leaving directory `/home2/ISAD/ks575/software/Annotation_Pipeline/PASA/PASApipeline-2.0.2/cdbtools/cdbfasta'
make: *** [all] Error 2
```

Any suggestions?
My system specifications are:
Linux minerva 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Thanks.

Kumar

**Comment by brianjohnhaas** [comment]
I'm not sure why this is happening. You can try 

  cd cdbtools/cdbfasta 

  make
   cp cdbfasta ../../bin/.
   cp cdbyank ../../bin/.

directly and see how that goes, and then skip that section of the Makefile.

**Comment by kumarsaurabh20** [comment]
I tried what you are recommending....but to no avail. I think, as this solution suggests (http://stackoverflow.com/questions/2100448/multiple-target-patterns-makefile-error), it could be some indentation or escape character issue. I also checked by replacing some of the characters but did not pass through that error. I wonder why this issue is not being reported anywhere or there is a problem with my Ubuntu distribution because it worked on Centos.  Or is it a compiling/builder program version issue?

**Comment by brianjohnhaas** [comment]
What's the error you're getting when you try to build the cdbtools
separately?



On Tue, Jul 12, 2016 at 8:05 AM, JstRoRR <notifications@github.com> wrote:

> I tried what you are recommending....but to no avail. I think, as this
> solution suggests (
> http://stackoverflow.com/questions/2100448/multiple-target-patterns-makefile-error),
> it could be some indentation or escape character issue. I also checked by
> replacing some of the characters but did not pass through that error. I
> wonder why this issue is not being reported anywhere or there is a problem
> with my Ubuntu distribution because it worked on Centos. Or is it a
> compiling/builder program version issue?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/PASApipeline/PASApipeline/issues/19#issuecomment-232027409>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHMVXx3sAixFM31UW6ya00Br48fIj98Uks5qU4LtgaJpZM4JCXsS>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by kumarsaurabh20** [comment]
Hi Brian..here is the output...

ks575@rstudio03:~/software/PASA/PASApipeline-2.0.2/cdbtools/cdbfasta$ make
Makefile:42: *** multiple target patterns. Stop.

**Comment by brianjohnhaas** [comment]
I haven't encountered that error before.  From googling it:

https://www.eclipse.org/forums/index.php/t/59741/

and there's other info on it from google that might help.

The cdbtools are 3rd party software from
http://sourceforge.net/projects/cdbfasta/files/

You can also try pulling it down from there and see if you can build it.

~b

On Wed, Jul 13, 2016 at 4:49 AM, JstRoRR <notifications@github.com> wrote:

> Hi Brian..here is the output...
>
> ks575@rstudio03:~/software/PASA/PASApipeline-2.0.2/cdbtools/cdbfasta$ make
> Makefile:42: *** multiple target patterns. Stop.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/PASApipeline/PASApipeline/issues/19#issuecomment-232295638>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHMVXxSG2Jgtvm2K5LIQvJTjJm3qWHUTks5qVKZ9gaJpZM4JCXsS>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by kumarsaurabh20** [comment]
Thanks for your suggestions Brian. I will have a look at it.

Kumar

**Comment by kumarsaurabh20** [comment]
Hi Brian,

I have found the bug. my $LIBS environment variable was creating problems. It had multiple paths separated by : with -L in the beginning. I just emptied the LIBS env variable and everything worked like a charm. 

I think you can close this issue.

**Comment by brianjohnhaas** [comment]
Terrific!  Thx

-Brian
(by iPhone)
