### ISSUE TITLE
ERROR, transcript *** found with alignment but not recognized in the transcript database

### ISSUE THREAD

**Issue by tinyhys** [PASApipeline/PASApipeline#208]
![image](https://user-images.githubusercontent.com/37066354/130910623-18f1866b-5a68-41ce-ae4b-fc689f468c1c.png)
Dear developer,
  Thanks to your excellent tools!
  I used minimap2 in the pipeline and after alignment there emerged 11778 lines saying 
ERROR, transcript XXX.p1 found with alignment but not recognized in the transcript database 
in the nohup.out file while the number accounted for ~3% of the sequence in my combined trans.fa file. 
Before the run I have changed the prefix of the ref-guided transcript to 'ref' and 'denovo' for de novo assembled one, but no suffix like 'p1'. 
The run haven't finished yet as it is now running the CMD 
"/home/software/pasa/scripts/set_spliced_orient_transcribed_orient.dbi -M '/sdc1/yty/murraya.anno/pasa/pasa.rename/pasadb' > pasa_run.log.dir/setting_aligned_as_transcribed_orientation.output"
is there anything I met which would do harm for the results so I should stop it and rerun the pipe after debugging?
~forgive my poor English && appreciate for any reply!

**Comment by aic123** [comment]
ERROR, transcript *.p1 found with alignment but not recognized in the transcript database

I have the same problem when run pasa with minimap2
Did you solve this problem?

**Comment by brianjohnhaas** [comment]
hi,

are you using the latest software release?

Also, if you examine the alignment.validations.output  output file (grep
for minimap) are you seeing the .p1 suffix in the accessions?  Also, do you
see minimap2 alignments as passing validation criteria?

best,

~b

On Mon, Sep 13, 2021 at 3:47 AM aic123 ***@***.***> wrote:
>
> ERROR, transcript *.p1 found with alignment but not recognized in the
transcript database
>
> I have the same problem when run pasa with minimap2
> Did you solve this problem?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.



--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas

**Comment by aic123** [comment]
Yes, PASA version is 2.5.1

.p1 suffix  are in database.valid_minimap2_alignments.bed and database.valid_minimap2_alignments.gtf， but not in database.valid_minimap2_alignments.gff3

# database.valid_minimap2_alignments.bed
ctg2544      4062347 4062827 ID=H01-transcript/c32537/f1/485,H01-transcript/c32537/f1/485.p1 0       -       4062347 4062827 0       1       480     0

#database.valid_minimap2_alignments.gtf：
ctg1      minimap2        transcript      159789  160162  .       +       .       gene_id "align_id:1|H01-transcript/c711991/f1/387"; transcript_id "align_id:1|H01-transcript/c711991/f1/387|H01-transcript/c711991/f1/387.p1";

#database.valid_minimap2_alignments.gff3
ctg1      minimap2-database      cDNA_match      159789  160162  97.1    +       .       ID=align_1;Target=H01-transcript/c711991/f1/387 1 375 +

And, The transcript ids  appeared in the error message  can be found in database.failed_minimap2_alignments.gtf

Hope this information is helpful.

**Comment by tinyhys** [comment]
> ERROR, transcript *.p1 found with alignment but not recognized in the transcript database
> 
> I have the same problem when run pasa with minimap2
> Did you solve this problem?

Sorry for late reply. It took a long time to run the command after a week using only one thread though 36 threads were allocated, and it did not seem to finish soon. Then I reviewed the guide and submitted another command without **--ALT_SPLICE** option, which accomplished ahead of the previous run. It ALSO warned the same ERROR. However it seems ignorable because the transcripts without recognition only represented a little part of all.
