### ISSUE TITLE
Error, cannot locate pasa binary

### ISSUE THREAD

**Issue by wangzhennan14** [PASApipeline/PASApipeline#21]
When I use the sample data to test PASA, there is an error, the command line I run is:
./run_sample_pipeline.pl

and the error is:
## Processing CMD: 30/40

23:31:35        CMD: /disk11/wangzhn/scorpion/software/PASApipeline-2.0.2/scripts/..//scripts/assemble_clusters.dbi -G genome_sample.fasta  -M sample_mydb_pasa  -T 2  > sample_mydb_pasa.pasa_alignment_assembly_building.ascii_illustrations.out
Error, cannot locate pasa binary.  at /disk11/wangzhn/scorpion/software/PASApipeline-2.0.2/scripts/..//scripts/assemble_clusters.dbi line 83.

ERROR: The following command died with exit code (256):
/disk11/wangzhn/scorpion/software/PASApipeline-2.0.2/scripts/..//scripts/assemble_clusters.dbi -G genome_sample.fasta  -M sample_mydb_pasa  -T 2  > sample_mydb_pasa.pasa_alignment_assembly_building.ascii_illustrations.out

Must re-run pipeline starting at index [30] via running Launch_PASA_pipeline with parameter '-s 30' (exclude param '-C' since db already created)

Error, cmd: ../scripts/Launch_PASA_pipeline.pl -c alignAssembly.config -C -r -R -g genome_sample.fasta -t all_transcripts.fasta.clean -T -u all_transcripts.fasta -f FL_accs.txt --ALIGNERS blat,gmap --CPU 2 -N 2 --TDN tdn.accs  --IMPORT_CUSTOM_ALIGNMENTS_GFF3 custom_alignments.gff3  died with ret(6400)  at ./run_sample_pipeline.pl line 186.

Can you tell me how to solve this problem? Thank you.

**Comment by brianjohnhaas** [comment]
Hi

Did you build all the tools by running 

   make

in the base pasa software directory? 

-Brian
(by iPhone)

**Comment by wangzhennan14** [comment]
dear brianjohnhaas,
          
        Thank you for your help, but when I use the sample data tu run ./run_sample_pipeline.pl, there is an error, and I can not understand.

       ## Processing CMD:
21:35:09        CMD: /disk11/wangzhn/scorpion/software/pasa/scripts/..//scripts/Load_Current_Gene_Annotations.dbi -c annotCompare.config -g genome_sample.fasta -P orig_annotations_sample.gff3  > pasa_run.log.dir/output.annot_loading.55579.out
perl: symbol lookup error: /usr/local/bin/perl/site/lib/auto/DB_File/DB_File.so: undefined symbol: db_version
Use of uninitialized value $index in concatenation (.) or string at ../scripts/Launch_PASA_pipeline.pl line 981.
Use of uninitialized value $index in concatenation (.) or string at ../scripts/Launch_PASA_pipeline.pl line 981.


ERROR: The following command died with exit code (32512):
/disk11/wangzhn/scorpion/software/pasa/scripts/..//scripts/Load_Current_Gene_Annotations.dbi -c annotCompare.config -g genome_sample.fasta -P orig_annotations_sample.gff3  > pasa_run.log.dir/output.annot_loading.55579.out

Must re-run pipeline starting at index [] via running Launch_PASA_pipeline with parameter '-s ' (exclude param '-C' since db already created)

Error, cmd: ../scripts/Launch_PASA_pipeline.pl -c annotCompare.config -g genome_sample.fasta -t all_transcripts.fasta.clean -A -L --annots_gff3 orig_annotations_sample.gff3 --CPU 2 died with ret(32512)  at ./run_sample_pipeline.pl line 186.


             I have read the output.annot_loading.55579.out, in this file , there is one message, I do not know what does it mean,

             CMD: /disk11/wangzhn/scorpion/software/pasa/scripts/..//scripts/Annotation_store_preloader.dbi -c annotCompare.config


             How to deal with this problem? Can you help me to solve it? Thank you!

                                                                                                                                                                                                                                                                                                               wang
