### ISSUE TITLE
when I use Load_Current_Gene_Annotations.dbi to load my data, there is an error

### ISSUE THREAD

**Issue by wangzhennan14** [PASApipeline/PASApipeline#23]
Hi,
    When I use the command :
../scripts/Load_Current_Gene_Annotations.dbi -c alignAssembly.config -g MM.fa -P gene-models-v1.0.gff

There is an error, and I do not know how to deal with it.
Error, no gene feature found for CDS.... ignoring feature.
Error, no gene feature found for CDS.... ignoring feature.
Error, no gene feature found for CDS.... ignoring feature.
Error, no gene feature found for CDS.... ignoring feature.
Error, no gene feature found for CDS.... ignoring feature.
Error, no gene feature found for CDS.... ignoring feature.
Error, no gene feature found for CDS.... ignoring feature.
Error, no gene feature found for CDS.... ignoring feature.
Error, no gene feature found for CDS.... ignoring feature.
Error, no gene feature found for CDS.... ignoring feature.
Error, no gene feature found for CDS.... ignoring feature.
Error, no gene feature found for CDS.... ignoring feature.
Error, no gene feature found for CDS.... ignoring feature.
.............
Warning, no genes retrieved for contig_id: Contig339368.2
Warning, no genes retrieved for contig_id: Contig339890.2
Warning, no genes retrieved for contig_id: Contig339976.2
Warning, no genes retrieved for contig_id: Contig340433.2
Warning, no genes retrieved for contig_id: Contig347958.2
Warning, no genes retrieved for contig_id: Contig348149.2
Warning, no genes retrieved for contig_id: Contig351668.2
Warning, no genes retrieved for contig_id: Contig246961.2
Warning, no genes retrieved for contig_id: Contig248355.2
Warning, no genes retrieved for contig_id: Contig277135.2
Warning, no genes retrieved for contig_id: Contig289018.2
Warning, no genes retrieved for contig_id: Contig294273.2
Warning, no genes retrieved for contig_id: Contig312524.2
Warning, no genes retrieved for contig_id: Contig322419.2
Warning, no genes retrieved for contig_id: Contig333367.2

Can you help me to solve this problem? Thank you.

**Comment by brianjohnhaas** [comment]
Hi

The gff3 formatting of the annotation file is critical.  Check the provided example data and see how your annotation file formatting compares.

Best,

-Brian
(by iPhone)

**Comment by wangzhennan14** [comment]
Thank you very much!!
