### ISSUE TITLE
error when installing PASA on Ubuntu 16.10

### ISSUE THREAD

**Issue by MichaelFokinNZ** [PASApipeline/PASApipeline#30]
make leads to the following.... :(

> 
> > make[1]: Entering directory '/home/osboxes/PhD_pasa/PASApipeline-2.0.2/pasa_cpp'
> > g++ -O3  -c alignment_segment.cpp -o alignment_segment.o 
> > g++ -O3  -c cdna_alignment.cpp -o cdna_alignment.o 
> > g++ -O3  -c common_subs.cpp -o common_subs.o 
> > g++ -O3  -c cdna_alignment_assembler.cpp -o cdna_alignment_assembler.o 
> > g++ -O3  -c Lobject.cpp -o Lobject.o 
> > g++ -O3  -c stringFuncts.cpp -o stringFuncts.o 
> > g++ -O3  -c pasa.cpp -o pasa.o 
> > pasa.cpp: In function ‘int main(int, char**)’:
> > pasa.cpp:37:18: error: no match for ‘operator==’ (operand types are ‘std::ifstream {aka std::basic_ifstream<char>}’ and ‘int’)
> >  if (fileReader == 0) { // couldn't open file
> pasa.cpp:37:18: note: candidate: operator==(int, int) <built-in>
> pasa.cpp:37:18: note:   no known conversion for argument 1 from ‘std::ifstream {aka std::basic_ifstream<char>}’ to ‘int’
> In file included from /usr/include/c++/6/iosfwd:40:0,
>                  from /usr/include/c++/6/ios:38,
>                  from /usr/include/c++/6/ostream:38,
>                  from /usr/include/c++/6/iostream:39,
>                  from cdna_alignment.h:1,
>                  from pasa.cpp:5:
> /usr/include/c++/6/bits/postypes.h:216:5: note: candidate: template<class _StateT> bool std::operator==(const std::fpos<_StateT>&, const std::fpos<_StateT>&)
>      operator==(const fpos<_StateT>& __lhs, const fpos<_StateT>& __rhs)
>      ^~~~~~~~
> /usr/include/c++/6/bits/postypes.h:216:5: note:   template argument deduction/substitution failed:
> pasa.cpp:37:21: note:   ‘std::ifstream {aka std::basic_ifstream<char>}’ is not derived from ‘const std::fpos<_StateT>’
>    if (fileReader == 0) { // couldn't open file
>                      ^
> In file included from /usr/include/c++/6/bits/stl_algobase.h:64:0,
>                  from /usr/include/c++/6/bits/char_traits.h:39,
>                  from /usr/include/c++/6/ios:40,
>                  from /usr/include/c++/6/ostream:38,
>                  from /usr/include/c++/6/iostream:39,
>                  from cdna_alignment.h:1,
>                  from pasa.cpp:5:
> /usr/include/c++/6/bits/stl_pair.h:431:5: note: candidate: template<class _T1, class _T2> constexpr bool std::operator==(const std::pair<_T1, _T2>&, const std::pair<_T1, _T2>&)
>      operator==(const pair<_T1, _T2>& __x, const pair<_T1, _T2>& __y)
>      ^~~~~~~~
> /usr/include/c++/6/bits/stl_pair.h:431:5: note:   template argument deduction/substitution failed:
> pasa.cpp:37:21: note:   ‘std::ifstream {aka std::basic_ifstream<char>}’ is not derived from ‘const std::pair<_T1, _T2>’
>    if (fileReader == 0) { // couldn't open file
>                      ^
> In file included from /usr/include/c++/6/bits/stl_algobase.h:67:0,
>                  from /usr/include/c++/6/bits/char_traits.h:39,
>                  from /usr/include/c++/6/ios:40,
>                  from /usr/include/c++/6/ostream:38,
>                  from /usr/include/c++/6/iostream:39,
>                  from cdna_alignment.h:1,
>                  from pasa.cpp:5:
> /usr/include/c++/6/bits/stl_iterator.h:292:5: note: candidate: template<class _Iterator> bool std::operator==(const std::reverse_iterator<_Iterator>&, const std::reverse_iterator<_Iterator>&)
>      operator==(const reverse_iterator<_Iterator>& __x,
>      ^~~~~~~~
> /usr/include/c++/6/bits/stl_iterator.h:292:5: note:   template argument deduction/substitution failed:
> pasa.cpp:37:21: note:   ‘std::ifstream {aka std::basic_ifstream<char>}’ is not derived from ‘const std::reverse_iterator<_Iterator>’
>    if (fileReader == 0) { // couldn't open file
>                      ^
> In file included from /usr/include/c++/6/bits/stl_algobase.h:67:0,
>                  from /usr/include/c++/6/bits/char_traits.h:39,
>                  from /usr/include/c++/6/ios:40,
>                  from /usr/include/c++/6/ostream:38,
>                  from /usr/include/c++/6/iostream:39,
>                  from cdna_alignment.h:1,
>                  from pasa.cpp:5:
> /usr/include/c++/6/bits/stl_iterator.h:349:5: note: candidate: template<class _IteratorL, class _IteratorR> bool std::operator==(const std::reverse_iterator<_Iterator>&, const std::reverse_iterator<_IteratorR>&)
>      operator==(const reverse_iterator<_IteratorL>& __x,
>      ^~~~~~~~
> /usr/include/c++/6/bits/stl_iterator.h:349:5: note:   template argument deduction/substitution failed:
> pasa.cpp:37:21: note:   ‘std::ifstream {aka std::basic_ifstream<char>}’ is not derived from ‘const std::reverse_iterator<_Iterator>’
>    if (fileReader == 0) { // couldn't open file
>                      ^
> In file included from /usr/include/c++/6/bits/stl_algobase.h:67:0,
>                  from /usr/include/c++/6/bits/char_traits.h:39,
>                  from /usr/include/c++/6/ios:40,
>                  from /usr/include/c++/6/ostream:38,
>                  from /usr/include/c++/6/iostream:39,
>                  from cdna_alignment.h:1,
>                  from pasa.cpp:5:
> /usr/include/c++/6/bits/stl_iterator.h:1113:5: note: candidate: template<class _IteratorL, class _IteratorR> bool std::operator==(const std::move_iterator<_IteratorL>&, const std::move_iterator<_IteratorR>&)
>      operator==(const move_iterator<_IteratorL>& __x,
>      ^~~~~~~~
> /usr/include/c++/6/bits/stl_iterator.h:1113:5: note:   template argument deduction/substitution failed:
> pasa.cpp:37:21: note:   ‘std::ifstream {aka std::basic_ifstream<char>}’ is not derived from ‘const std::move_iterator<_IteratorL>’
>    if (fileReader == 0) { // couldn't open file
>                      ^
> In file included from /usr/include/c++/6/bits/stl_algobase.h:67:0,
>                  from /usr/include/c++/6/bits/char_traits.h:39,
>                  from /usr/include/c++/6/ios:40,
>                  from /usr/include/c++/6/ostream:38,
>                  from /usr/include/c++/6/iostream:39,
>                  from cdna_alignment.h:1,
>                  from pasa.cpp:5:
> /usr/include/c++/6/bits/stl_iterator.h:1119:5: note: candidate: template<class _Iterator> bool std::operator==(const std::move_iterator<_IteratorL>&, const std::move_iterator<_IteratorL>&)
>      operator==(const move_iterator<_Iterator>& __x,
>      ^~~~~~~~
> /usr/include/c++/6/bits/stl_iterator.h:1119:5: note:   template argument deduction/substitution failed:
> pasa.cpp:37:21: note:   ‘std::ifstream {aka std::basic_ifstream<char>}’ is not derived from ‘const std::move_iterator<_IteratorL>’
>    if (fileReader == 0) { // couldn't open file
>                      ^
> In file included from /usr/include/c++/6/string:41:0,
>                  from /usr/include/c++/6/bits/locale_classes.h:40,
>                  from /usr/include/c++/6/bits/ios_base.h:41,
>                  from /usr/include/c++/6/ios:42,
>                  from /usr/include/c++/6/ostream:38,
>                  from /usr/include/c++/6/iostream:39,
>                  from cdna_alignment.h:1,
>                  from pasa.cpp:5:
> /usr/include/c++/6/bits/allocator.h:133:5: note: candidate: template<class _T1, class _T2> bool std::operator==(const std::allocator<_CharT>&, const std::allocator<_T2>&)
>      operator==(const allocator<_T1>&, const allocator<_T2>&)
>      ^~~~~~~~
> /usr/include/c++/6/bits/allocator.h:133:5: note:   template argument deduction/substitution failed:
> pasa.cpp:37:21: note:   ‘std::ifstream {aka std::basic_ifstream<char>}’ is not derived from ‘const std::allocator<_CharT>’
>    if (fileReader == 0) { // couldn't open file
>                      ^
> In file included from /usr/include/c++/6/string:41:0,
>                  from /usr/include/c++/6/bits/locale_classes.h:40,
>                  from /usr/include/c++/6/bits/ios_base.h:41,
>                  from /usr/include/c++/6/ios:42,
>                  from /usr/include/c++/6/ostream:38,
>                  from /usr/include/c++/6/iostream:39,
>                  from cdna_alignment.h:1,
>                  from pasa.cpp:5:
> /usr/include/c++/6/bits/allocator.h:139:5: note: candidate: template<class _Tp> bool std::operator==(const std::allocator<_CharT>&, const std::allocator<_CharT>&)
>      operator==(const allocator<_Tp>&, const allocator<_Tp>&)
>      ^~~~~~~~
> /usr/include/c++/6/bits/allocator.h:139:5: note:   template argument deduction/substitution failed:
> pasa.cpp:37:21: note:   ‘std::ifstream {aka std::basic_ifstream<char>}’ is not derived from ‘const std::allocator<_CharT>’
>    if (fileReader == 0) { // couldn't open file
>                      ^
> In file included from /usr/include/c++/6/string:52:0,
>                  from /usr/include/c++/6/bits/locale_classes.h:40,
>                  from /usr/include/c++/6/bits/ios_base.h:41,
>                  from /usr/include/c++/6/ios:42,
>                  from /usr/include/c++/6/ostream:38,
>                  from /usr/include/c++/6/iostream:39,
>                  from cdna_alignment.h:1,
>                  from pasa.cpp:5:
> /usr/include/c++/6/bits/basic_string.h:5050:5: note: candidate: template<class _CharT, class _Traits, class _Alloc> bool std::operator==(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&, const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&)
>      operator==(const basic_string<_CharT, _Traits, _Alloc>& __lhs,
>      ^~~~~~~~
> /usr/include/c++/6/bits/basic_string.h:5050:5: note:   template argument deduction/substitution failed:
> pasa.cpp:37:21: note:   ‘std::ifstream {aka std::basic_ifstream<char>}’ is not derived from ‘const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>’
>    if (fileReader == 0) { // couldn't open file
>                      ^
> In file included from /usr/include/c++/6/string:52:0,
>                  from /usr/include/c++/6/bits/locale_classes.h:40,
>                  from /usr/include/c++/6/bits/ios_base.h:41,
>                  from /usr/include/c++/6/ios:42,
>                  from /usr/include/c++/6/ostream:38,
>                  from /usr/include/c++/6/iostream:39,
>                  from cdna_alignment.h:1,
>                  from pasa.cpp:5:
> /usr/include/c++/6/bits/basic_string.h:5058:5: note: candidate: template<class _CharT> typename __gnu_cxx::__enable_if<std::__is_char<_Tp>::__value, bool>::__type std::operator==(const std::__cxx11::basic_string<_CharT>&, const std::__cxx11::basic_string<_CharT>&)
>      operator==(const basic_string<_CharT>& __lhs,
>      ^~~~~~~~
> /usr/include/c++/6/bits/basic_string.h:5058:5: note:   template argument deduction/substitution failed:
> pasa.cpp:37:21: note:   ‘std::ifstream {aka std::basic_ifstream<char>}’ is not derived from ‘const std::__cxx11::basic_string<_CharT>’
>    if (fileReader == 0) { // couldn't open file
>                      ^
> In file included from /usr/include/c++/6/string:52:0,
>                  from /usr/include/c++/6/bits/locale_classes.h:40,
>                  from /usr/include/c++/6/bits/ios_base.h:41,
>                  from /usr/include/c++/6/ios:42,
>                  from /usr/include/c++/6/ostream:38,
>                  from /usr/include/c++/6/iostream:39,
>                  from cdna_alignment.h:1,
>                  from pasa.cpp:5:
> /usr/include/c++/6/bits/basic_string.h:5072:5: note: candidate: template<class _CharT, class _Traits, class _Alloc> bool std::operator==(const _CharT*, const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&)
>      operator==(const _CharT* __lhs,
>      ^~~~~~~~
> /usr/include/c++/6/bits/basic_string.h:5072:5: note:   template argument deduction/substitution failed:
> pasa.cpp:37:21: note:   mismatched types ‘const _CharT*’ and ‘std::basic_ifstream<char>’
>    if (fileReader == 0) { // couldn't open file
>                      ^
> In file included from /usr/include/c++/6/string:52:0,
>                  from /usr/include/c++/6/bits/locale_classes.h:40,
>                  from /usr/include/c++/6/bits/ios_base.h:41,
>                  from /usr/include/c++/6/ios:42,
>                  from /usr/include/c++/6/ostream:38,
>                  from /usr/include/c++/6/iostream:39,
>                  from cdna_alignment.h:1,
>                  from pasa.cpp:5:
> /usr/include/c++/6/bits/basic_string.h:5084:5: note: candidate: template<class _CharT, class _Traits, class _Alloc> bool std::operator==(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&, const _CharT*)
>      operator==(const basic_string<_CharT, _Traits, _Alloc>& __lhs,
>      ^~~~~~~~
> /usr/include/c++/6/bits/basic_string.h:5084:5: note:   template argument deduction/substitution failed:
> pasa.cpp:37:21: note:   ‘std::ifstream {aka std::basic_ifstream<char>}’ is not derived from ‘const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>’
>    if (fileReader == 0) { // couldn't open file
>                      ^
> In file included from /usr/include/c++/6/bits/ios_base.h:46:0,
>                  from /usr/include/c++/6/ios:42,
>                  from /usr/include/c++/6/ostream:38,
>                  from /usr/include/c++/6/iostream:39,
>                  from cdna_alignment.h:1,
>                  from pasa.cpp:5:
> /usr/include/c++/6/system_error:284:3: note: candidate: bool std::operator==(const std::error_code&, const std::error_code&)
>    operator==(const error_code& __lhs, const error_code& __rhs) noexcept
>    ^~~~~~~~
> /usr/include/c++/6/system_error:284:3: note:   no known conversion for argument 1 from ‘std::ifstream {aka std::basic_ifstream<char>}’ to ‘const std::error_code&’
> /usr/include/c++/6/system_error:289:3: note: candidate: bool std::operator==(const std::error_code&, const std::error_condition&)
>    operator==(const error_code& __lhs, const error_condition& __rhs) noexcept
>    ^~~~~~~~
> /usr/include/c++/6/system_error:289:3: note:   no known conversion for argument 1 from ‘std::ifstream {aka std::basic_ifstream<char>}’ to ‘const std::error_code&’
> /usr/include/c++/6/system_error:296:3: note: candidate: bool std::operator==(const std::error_condition&, const std::error_code&)
>    operator==(const error_condition& __lhs, const error_code& __rhs) noexcept
>    ^~~~~~~~
> /usr/include/c++/6/system_error:296:3: note:   no known conversion for argument 1 from ‘std::ifstream {aka std::basic_ifstream<char>}’ to ‘const std::error_condition&’
> /usr/include/c++/6/system_error:303:3: note: candidate: bool std::operator==(const std::error_condition&, const std::error_condition&)
>    operator==(const error_condition& __lhs,
>    ^~~~~~~~
> /usr/include/c++/6/system_error:303:3: note:   no known conversion for argument 1 from ‘std::ifstream {aka std::basic_ifstream<char>}’ to ‘const std::error_condition&’
> In file included from /usr/include/c++/6/bits/locale_facets.h:48:0,
>                  from /usr/include/c++/6/bits/basic_ios.h:37,
>                  from /usr/include/c++/6/ios:44,
>                  from /usr/include/c++/6/ostream:38,
>                  from /usr/include/c++/6/iostream:39,
>                  from cdna_alignment.h:1,
>                  from pasa.cpp:5:
> /usr/include/c++/6/bits/streambuf_iterator.h:204:5: note: candidate: template<class _CharT, class _Traits> bool std::operator==(const std::istreambuf_iterator<_CharT, _Traits>&, const std::istreambuf_iterator<_CharT, _Traits>&)
>      operator==(const istreambuf_iterator<_CharT, _Traits>& __a,
>      ^~~~~~~~
> /usr/include/c++/6/bits/streambuf_iterator.h:204:5: note:   template argument deduction/substitution failed:
> pasa.cpp:37:21: note:   ‘std::ifstream {aka std::basic_ifstream<char>}’ is not derived from ‘const std::istreambuf_iterator<_CharT, _Traits>’
>    if (fileReader == 0) { // couldn't open file
>                      ^
> In file included from /usr/include/c++/6/vector:64:0,
>                  from cdna_alignment.h:3,
>                  from pasa.cpp:5:
> /usr/include/c++/6/bits/stl_vector.h:1509:5: note: candidate: template<class _Tp, class _Alloc> bool std::operator==(const std::vector<_Tp, _Alloc>&, const std::vector<_Tp, _Alloc>&)
>      operator==(const vector<_Tp, _Alloc>& __x, const vector<_Tp, _Alloc>& __y)
>      ^~~~~~~~
> /usr/include/c++/6/bits/stl_vector.h:1509:5: note:   template argument deduction/substitution failed:
> pasa.cpp:37:21: note:   ‘std::ifstream {aka std::basic_ifstream<char>}’ is not derived from ‘const std::vector<_Tp, _Alloc>’
>    if (fileReader == 0) { // couldn't open file
>                      ^
> In file included from /usr/include/c++/6/map:60:0,
>                  from Lobject.h:4,
>                  from cdna_alignment_assembler.h:4,
>                  from pasa.cpp:7:
> /usr/include/c++/6/bits/stl_tree.h:328:5: note: candidate: template<class _Val> bool std::operator==(const std::_Rb_tree_iterator<_Tp>&, const std::_Rb_tree_const_iterator<_Val>&)
>      operator==(const _Rb_tree_iterator<_Val>& __x,
>      ^~~~~~~~
> /usr/include/c++/6/bits/stl_tree.h:328:5: note:   template argument deduction/substitution failed:
> pasa.cpp:37:21: note:   ‘std::ifstream {aka std::basic_ifstream<char>}’ is not derived from ‘const std::_Rb_tree_iterator<_Tp>’
>    if (fileReader == 0) { // couldn't open file
>                      ^
> In file included from /usr/include/c++/6/map:60:0,
>                  from Lobject.h:4,
>                  from cdna_alignment_assembler.h:4,
>                  from pasa.cpp:7:
> /usr/include/c++/6/bits/stl_tree.h:1282:5: note: candidate: template<class _Key, class _Val, class _KeyOfValue, class _Compare, class _Alloc> bool std::operator==(const std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>&, const std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>&)
>      operator==(const _Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>& __x,
>      ^~~~~~~~
> /usr/include/c++/6/bits/stl_tree.h:1282:5: note:   template argument deduction/substitution failed:
> pasa.cpp:37:21: note:   ‘std::ifstream {aka std::basic_ifstream<char>}’ is not derived from ‘const std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>’
>    if (fileReader == 0) { // couldn't open file
>                      ^
> In file included from /usr/include/c++/6/tuple:39:0,
>                  from /usr/include/c++/6/bits/stl_map.h:63,
>                  from /usr/include/c++/6/map:61,
>                  from Lobject.h:4,
>                  from cdna_alignment_assembler.h:4,
>                  from pasa.cpp:7:
> /usr/include/c++/6/array:241:5: note: candidate: template<class _Tp, long unsigned int _Nm> bool std::operator==(const std::array<_Tp, _Nm>&, const std::array<_Tp, _Nm>&)
>      operator==(const array<_Tp, _Nm>& __one, const array<_Tp, _Nm>& __two)
>      ^~~~~~~~
> /usr/include/c++/6/array:241:5: note:   template argument deduction/substitution failed:
> pasa.cpp:37:21: note:   ‘std::ifstream {aka std::basic_ifstream<char>}’ is not derived from ‘const std::array<_Tp, _Nm>’
>    if (fileReader == 0) { // couldn't open file
>                      ^
> In file included from /usr/include/c++/6/bits/stl_map.h:63:0,
>                  from /usr/include/c++/6/map:61,
>                  from Lobject.h:4,
>                  from cdna_alignment_assembler.h:4,
>                  from pasa.cpp:7:
> /usr/include/c++/6/tuple:1337:5: note: candidate: template<class ... _TElements, class ... _UElements> constexpr bool std::operator==(const std::tuple<_Args1 ...>&, const std::tuple<_Args2 ...>&)
>      operator==(const tuple<_TElements...>& __t,
>      ^~~~~~~~
> /usr/include/c++/6/tuple:1337:5: note:   template argument deduction/substitution failed:
> pasa.cpp:37:21: note:   ‘std::ifstream {aka std::basic_ifstream<char>}’ is not derived from ‘const std::tuple<_Args1 ...>’
>    if (fileReader == 0) { // couldn't open file
>                      ^
> In file included from /usr/include/c++/6/map:61:0,
>                  from Lobject.h:4,
>                  from cdna_alignment_assembler.h:4,
>                  from pasa.cpp:7:
> /usr/include/c++/6/bits/stl_map.h:1307:5: note: candidate: template<class _Key, class _Tp, class _Compare, class _Alloc> bool std::operator==(const std::map<_Key, _Tp, _Compare, _Alloc>&, const std::map<_Key, _Tp, _Compare, _Alloc>&)
>      operator==(const map<_Key, _Tp, _Compare, _Alloc>& __x,
>      ^~~~~~~~
> /usr/include/c++/6/bits/stl_map.h:1307:5: note:   template argument deduction/substitution failed:
> pasa.cpp:37:21: note:   ‘std::ifstream {aka std::basic_ifstream<char>}’ is not derived from ‘const std::map<_Key, _Tp, _Compare, _Alloc>’
>    if (fileReader == 0) { // couldn't open file
>                      ^
> In file included from /usr/include/c++/6/map:62:0,
>                  from Lobject.h:4,
>                  from cdna_alignment_assembler.h:4,
>                  from pasa.cpp:7:
> /usr/include/c++/6/bits/stl_multimap.h:972:5: note: candidate: template<class _Key, class _Tp, class _Compare, class _Alloc> bool std::operator==(const std::multimap<_Key, _Tp, _Compare, _Alloc>&, const std::multimap<_Key, _Tp, _Compare, _Alloc>&)
>      operator==(const multimap<_Key, _Tp, _Compare, _Alloc>& __x,
>      ^~~~~~~~
> /usr/include/c++/6/bits/stl_multimap.h:972:5: note:   template argument deduction/substitution failed:
> pasa.cpp:37:21: note:   ‘std::ifstream {aka std::basic_ifstream<char>}’ is not derived from ‘const std::multimap<_Key, _Tp, _Compare, _Alloc>’
>    if (fileReader == 0) { // couldn't open file
>                      ^
> Makefile:38: recipe for target 'pasa.o' failed
> make[1]: *** [pasa.o] Error 1
> make[1]: Leaving directory '/home/osboxes/PhD_pasa/PASApipeline-2.0.2/pasa_cpp'
> Makefile:3: recipe for target 'all' failed
> make: *** [all] Error 2
>

**Comment by MichaelFokinNZ** [comment]
the problem is on Ubuntu 16.10, but not on 14.04

**Comment by brianjohnhaas** [comment]
I've updated the code for the next release.
