### ISSUE TITLE
Documentation request: gmap DB

### ISSUE THREAD

**Issue by colindaven** [PASApipeline/PASApipeline#4]
Hi,

it seems you need to run the pipeline on an already created gmap database in the _same directory_ where you are running the script from ("-D ." in gmap command). 

I couldn't find a section of the documenation where gmap databases are dealt with. It would be great to have the command for this and a note that this needs to be in the same directory.

I was trying to run PASA on gmap builds in completely different directories without success ... also a "cannot find GMAP index" from the script would be nice at this position.

CMD: gmap -D . -d genome_sample.fasta.gmap all_transcripts.fasta.clean -f 3 -n 0 -x 50 -t 48 -B 5  --intronlength=500000 
GMAP version 2014-12-21 called with args: gmap -D . -d genome_sample.fasta.gmap all_transcripts.fasta.clean -f 3 -n 0 -x 50 -t 48 -B 5 --intronlength=500000

Gmap works after copying the database to the current dir and naming it as suggested by the sample 
files:
for:            genome_sample.fasta
gmap db : genome_sample.fasta.gmap

Thanks!
Colin

**Comment by brianjohnhaas** [comment]
Hi Colin,

Is this happening with the latest PASA on github?   I had made a change to
it recently (within the last couple of weeks) and I'm hoping this has been
resolved.

best,

~brian

On Tue, Feb 24, 2015 at 3:42 AM, colindaven <notifications@github.com>
wrote:

> Hi,
>
> it seems you need to run the pipeline on an already created gmap database
> in the *same directory* where you are running the script from ("-D ." in
> gmap command).
>
> I couldn't find a section of the documenation where gmap databases are
> dealt with. It would be great to have the command for this and a note that
> this needs to be in the same directory.
>
> I was trying to run PASA on gmap builds in completely different
> directories without success ... also a "cannot find GMAP index" from the
> script would be nice at this position.
>
> CMD: gmap -D . -d genome_sample.fasta.gmap all_transcripts.fasta.clean -f
> 3 -n 0 -x 50 -t 48 -B 5 --intronlength=500000
> GMAP version 2014-12-21 called with args: gmap -D . -d
> genome_sample.fasta.gmap all_transcripts.fasta.clean -f 3 -n 0 -x 50 -t 48
> -B 5 --intronlength=500000
>
> Gmap works after copying the database to the current dir and naming it as
> suggested by the sample
> files:
> for: genome_sample.fasta
> gmap db : genome_sample.fasta.gmap
>
> Thanks!
> Colin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PASApipeline/PASApipeline/issues/4>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by colindaven** [comment]
Hi Brian,

Yes, sorry, versions are:

git pull from today
gmap latest version  Part of GMAP package, version 2014-12-21

I think a few comments on gmap Dbs would be great on the website. 

Thanks and Best wishes,
Colin

**Comment by brianjohnhaas** [comment]
sure thing.  I'll aim to do this before the next release.

thx,

~brian


On Tue, Feb 24, 2015 at 11:03 AM, colindaven <notifications@github.com>
wrote:

> Hi Brian,
>
> Yes, sorry, versions are:
>
> git pull from today
> gmap latest version Part of GMAP package, version 2014-12-21
>
> I think a few comments on gmap Dbs would be great on the website.
>
> Thanks and Best wishes,
> Colin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PASApipeline/PASApipeline/issues/4#issuecomment-75784580>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
