### ISSUE TITLE
Gmap fails without error message if old data present 

### ISSUE THREAD

**Issue by colindaven** [PASApipeline/PASApipeline#5]
Hi Brian,

this one should be worth picking up on.
I didn't clean all the temporary files from previous runs and believe this caused a gmap issue.

I resolved it by moving the  gmap.spliced_alignments.gff3 somewhere else.
mv gmap.spliced_alignments.gff3* old/

Now gmap is running.

This could be detected in the perl script and perhaps removed (as it's just a temporary file, right?).

Thanks!
Colin

**Comment by brianjohnhaas** [comment]
Hi Colin,

Pasa tries to resume from earlier runs where possible.  It's always good to start a new run in a fresh working directory. Would this paradigm work?

Thx

-Brian
(by iPhone)

**Comment by colindaven** [comment]
Seems like a plan - thanks!
Colin
