### ISSUE TITLE
Compilation error on MacOSX (High Sierra v10.13.2 (17C205))

### ISSUE THREAD

**Issue by yjx1217** [PASApipeline/PASApipeline#54]
Hello,

I was trying to compile PASA v2.2.0 (commit a2c6169 ) on MacOSX (High Sierra v10.13.2 (17C205)) but encountered the following error:

pc5104:PASA yjx$ make
if [ ! -d bin ]; then mkdir bin; fi
cd pasa_cpp && /Applications/Xcode.app/Contents/Developer/usr/bin/make && cp pasa ../bin/.
g++ -O3  -c alignment_segment.cpp -o alignment_segment.o 
g++ -O3  -c cdna_alignment.cpp -o cdna_alignment.o 
g++ -O3  -c common_subs.cpp -o common_subs.o 
g++ -O3  -c cdna_alignment_assembler.cpp -o cdna_alignment_assembler.o 
g++ -O3  -c Lobject.cpp -o Lobject.o 
g++ -O3  -c stringFuncts.cpp -o stringFuncts.o 
g++ -O3  -c pasa.cpp -o pasa.o 
g++ -O3  -c argProcessor.cpp -o argProcessor.o 
argProcessor.cpp:25:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
1 warning generated.
g++ -o ./pasa alignment_segment.o cdna_alignment.o common_subs.o  cdna_alignment_assembler.o Lobject.o stringFuncts.o pasa.o argProcessor.o 
cd slclust && /Applications/Xcode.app/Contents/Developer/usr/bin/make && cp src/slclust ../bin/.
X=`pwd`; \
	for i in src; \
	do echo '<<<' $i '>>>'; cd $X/$i; make all; done
<<< src >>>
g++ -I../include -Wall  -c slcluster.cpp
In file included from slcluster.cpp:4:
../include/cmd_line_opts.h:1:9: warning: '__CMD_LINE_OPTS_H__' is used as a header guard here, followed by #define of a different macro
      [-Wheader-guard]
#ifndef __CMD_LINE_OPTS_H__
        ^~~~~~~~~~~~~~~~~~~
../include/cmd_line_opts.h:2:9: note: '__CMD_LiNE_OPTS_H__' is defined here; did you mean '__CMD_LINE_OPTS_H__'?
#define __CMD_LiNE_OPTS_H__
        ^~~~~~~~~~~~~~~~~~~
        __CMD_LINE_OPTS_H__
1 warning generated.
g++ -I../include -Wall  -c graph.cpp
g++ -I../include -Wall  -c graphnode.cpp
g++ -I../include -Wall  -c cmd_line_opts.cpp
In file included from cmd_line_opts.cpp:1:
../include/cmd_line_opts.h:1:9: warning: '__CMD_LINE_OPTS_H__' is used as a header guard here, followed by #define of a different macro
      [-Wheader-guard]
#ifndef __CMD_LINE_OPTS_H__
        ^~~~~~~~~~~~~~~~~~~
../include/cmd_line_opts.h:2:9: note: '__CMD_LiNE_OPTS_H__' is defined here; did you mean '__CMD_LINE_OPTS_H__'?
#define __CMD_LiNE_OPTS_H__
        ^~~~~~~~~~~~~~~~~~~
        __CMD_LINE_OPTS_H__
1 warning generated.
g++ -I../include -Wall  slcluster.o graph.o graphnode.o cmd_line_opts.o  -o slclust	
chmod 755 slclust
cd cdbtools/cdbfasta && /Applications/Xcode.app/Contents/Developer/usr/bin/make && cp cdbfasta ../../bin/. && cp cdbyank ../../bin/.
g++ -Wall -I- -I../zlib -I. -I../tgi_cl -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-exceptions -fno-rtti -D_REENTRANT  -c cdbfasta.cpp -o cdbfasta.o
clang: error: '-I-' not supported, please use -iquote instead
make[1]: *** [cdbfasta.o] Error 1
make: *** [all] Error 2

Could I have some suggestions on how to work around this problem? Thanks in advance!

Best,
Jia-Xing

**Comment by nathanweeks** [comment]
Hi @yjx1217 , I just fixed this (https://github.com/PASApipeline/PASApipeline/commit/3743a932faeb425c2943101d8729b63b6148a1c7). Could you please `git pull` to update your local master branch and try again?

**Comment by yjx1217** [comment]
It works! Many thanks Nathan! 

Best,
Jia-Xing

**Comment by nathanweeks** [comment]
Good to know! I'll go ahead close this issue.
