### ISSUE TITLE
An error with v2.2.0

### ISSUE THREAD

**Issue by wangzhennan14** [PASApipeline/PASApipeline#55]
Hi Brains,
     When I run run_sample_pipeline.pl, there was an error as follow. I have search the web, but I can not find methods to solve it? How can I to set mysql to solve this probles? Please give me some advice to run it successfully. Thank you very much.
The error,
ERROR 1071 (42000) at line 172 in file: '/vol2/agis/ruanjue_group/wangzhennan/software/PASApipeline-pasa-v2.2.0/schema/cdna_alignment_mysqlschema': Specified key was too long; max key length is 1000 bytes
CMD: /usr/bin/mysql  -uwangzhennan -pfyKb5QnA -hio1 -Dwangzhennan_data -e 'source /vol2/agis/ruanjue_group/wangzhennan/software/PASApipeline-pasa-v2.2.0/scripts/..//schema/cdna_alignment_mysqlschema' failed.
Use of uninitialized value $index in concatenation (.) or string at ../scripts/Launch_PASA_pipeline.pl line 997.
Use of uninitialized value $index in concatenation (.) or string at ../scripts/Launch_PASA_pipeline.pl line 997.

**Comment by nextgenusfs** [comment]
I had a similar error, you need to reduce the max key length in the mysql schema to get it to work, I tried 800 and that worked on my system. see more here https://github.com/PASApipeline/PASApipeline/issues/45

 i.e. modify the file at /vol2/agis/ruanjue_group/wangzhennan/software/PASApipeline-pasa-v2.2.0/schema/cdna_alignment_mysqlschema
```
--
-- Table structure for table 'annotation_updates'
--

CREATE TABLE annotation_updates (
  update_id int(11) NOT NULL auto_increment,
  gene_id varchar(1000) default NULL,
  model_id varchar(200) default NULL,
  alt_splice_flag tinyint(1) unsigned NOT NULL default '0',
  before_gene_obj mediumblob,
  after_gene_obj mediumblob,
  compare_id int(11) NOT NULL default '0',
  is_valid tinyint(1) unsigned NOT NULL default '0',
  have_before tinyint(1) unsigned NOT NULL default '0',
  have_after tinyint(1) unsigned NOT NULL default '0',
  is_novel_flag tinyint(1) unsigned default '0',
  PRIMARY KEY  (update_id),
  KEY is_valid_idx (is_valid),
  KEY alt_splice_idx (alt_splice_flag),
  KEY lotsastuff_idx (gene_id,model_id,is_valid,alt_splice_flag),
  KEY modelidx (model_id)
) ;
```
You will need to change the geneID as follows:
```
--
-- Table structure for table 'annotation_updates'
--

CREATE TABLE annotation_updates (
  update_id int(11) NOT NULL auto_increment,
  gene_id varchar(800) default NULL,
  model_id varchar(200) default NULL,
  alt_splice_flag tinyint(1) unsigned NOT NULL default '0',
  before_gene_obj mediumblob,
  after_gene_obj mediumblob,
  compare_id int(11) NOT NULL default '0',
  is_valid tinyint(1) unsigned NOT NULL default '0',
  have_before tinyint(1) unsigned NOT NULL default '0',
  have_after tinyint(1) unsigned NOT NULL default '0',
  is_novel_flag tinyint(1) unsigned default '0',
  PRIMARY KEY  (update_id),
  KEY is_valid_idx (is_valid),
  KEY alt_splice_idx (alt_splice_flag),
  KEY lotsastuff_idx (gene_id,model_id,is_valid,alt_splice_flag),
  KEY modelidx (model_id)
) ;
```
