### ISSUE TITLE
loading a transcript results on a error when ids are on DB

### ISSUE THREAD

**Issue by inti** [PASApipeline/PASApipeline#6]
Hi,
I had a pipeline run that was not completely finished. command was
```
$PASAHOME/scripts/Launch_PASA_pipeline.pl \
        -c alignAssembly.config \
        -R \
        -g /media/TeraData/ipedroso/globus_endpoint/Ptrichocarpa_phytozome/v3.0/assembly/Ptrichocarpa_210_v3.0.fa \
        -t /media/TeraData/ipedroso/globus_endpoint/Ptrichocarpa_phytozome/v3.0/annotation/Ptrichocarpa_210_v3.0.transcript.fa.clean \
        -T \
        -u /media/TeraData/ipedroso/globus_endpoint/Ptrichocarpa_phytozome/v3.0/annotation/Ptrichocarpa_210_v3.0.transcript.fa \
        -f FL_accs.txt \
        --ALIGNERS blat,gmap \
        -L --annots_gff3 <(zcat /media/TeraData/ipedroso/globus_endpoint/Ptrichocarpa_phytozome/v3.0/annotation/Ptrichocarpa_210_v3.0.gene_exons.gff3.gz) \
        --TDN ../trinity_de_novo/trinity_out_dir_run2/Trinity.fasta \
        --ALT_SPLICE \
        --CPU 20

```
 When I tried to re-started it says the database already exists. When modifying the options it complains that some of transcripts are already present on the database. 
```
[ipedroso@jimi PASA]$ $PASAHOME/scripts/Launch_PASA_pipeline.pl         -c alignAssembly.config         -R         -g /media/TeraData/ipedroso/globus_endpoint/Ptrichocarpa_phytozome/v3.0/assembly/Ptrichocarpa_210_v3.0.fa         -t /media/TeraData/ipedroso/globus_endpoint/Ptrichocarpa_phytozome/v3.0/annotation/Ptrichocarpa_210_v3.0.transcript.fa.clean         -T         -u /media/TeraData/ipedroso/globus_endpoint/Ptrichocarpa_phytozome/v3.0/annotation/Ptrichocarpa_210_v3.0.transcript.fa         -f FL_accs.txt         --ALIGNERS blat,gmap       --TDN ../trinity_de_novo/trinity_out_dir_run2/Trinity.fasta         --ALT_SPLICE         --CPU 20


## Processing CMD: 1/33
11:09:52        CMD: /home/ipedroso/APP/PASApipeline-2.0.1//scripts/upload_transcript_data.dbi -M Populus_trichocarpav3_2 -t /media/TeraData/ipedroso/globus_endpoint/Ptrichocarpa_phytozome/v3.0/annotation/Ptrichocarpa_210_v3.0.transcript.fa.clean -T ../trinity_de_novo/trinity_out_dir_run2/Trinity.fasta -f FL_accs.txt
DBD::mysql::db do failed: Duplicate entry 'Potri.T155100.1' for key 'cdna_acc_idx' at /home/ipedroso/APP/PASApipeline-2.0.1//PerlLib//Mysql_connect.pm line 162, <$filehandle> line 1.
failed query: < insert cdna_info (cdna_acc, is_assembly, is_fli, is_TDN, length, header) values (?,?,?,?,?,?) > values: Potri.T155100.1 0 1 0 830 Potri.T155100.1 pacid=26978278 locus=Potri.T155100 ID=Potri.T155100.1.v3.0 annot-version=v3.0
Errors: Duplicate entry 'Potri.T155100.1' for key 'cdna_acc_idx'
 at /home/ipedroso/APP/PASApipeline-2.0.1//PerlLib//Mysql_connect.pm line 173, <$filehandle> line 1.
        Mysql_connect::RunMod('Mysql_connect=HASH(0x11f8a38)', ' insert cdna_info (cdna_acc, is_assembly, is_fli, is_TDN, len...', 'Potri.T155100.1', 0, 1, 0, 830, 'Potri.T155100.1 pacid=26978278 locus=Potri.T155100 ID=Potri.T...') called at /home/ipedroso/APP/PASApipeline-2.0.1//scripts/upload_transcript_data.dbi line 97
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::mysql::db handle Populus_trichocarpav3_2:localhost at /usr/share/perl5/vendor_perl/Carp.pm line 101.


ERROR: The following command died with exit code (65280):
/home/ipedroso/APP/PASApipeline-2.0.1//scripts/upload_transcript_data.dbi -M Populus_trichocarpav3_2 -t /media/TeraData/ipedroso/globus_endpoint/Ptrichocarpa_phytozome/v3.0/annotation/Ptrichocarpa_210_v3.0.transcript.fa.clean -T ../trinity_de_novo/trinity_out_dir_run2/Trinity.fasta -f FL_accs.txt

Must re-run pipeline starting at index [1] via running Launch_PASA_pipeline with parameter '-s 1' (exclude param '-C' since db already created)

[ipedroso@jimi PASA]$

```
* What should I do when the previous run did not finished properly? Should I delete the transcripts from the db? 

* Is there a way that the pipeline either re-writes data on the db or simply detects it is there and carries on?

Thanks in advance!

**Comment by brianjohnhaas** [comment]
Hi,

If there's a crash partway through the pasa pipeline, you can restart it by
dropping the -C (create db) and including -s step  (integer number for the
step to resume at) - which PASA tells you at the crash point.

If you want to start at the very beginning, then you'll need to drop the
current database.  There's a way to do this by including options '-C -r' on
your restart, and it should allow you to restart from the very beginning,
removing the earlier database and recreating it.

best,

~brian



On Tue, Mar 17, 2015 at 10:56 AM, Inti Pedroso <notifications@github.com>
wrote:

> Hi,
> I had a pipeline run that was not completely finished. command was
>
> $PASAHOME/scripts/Launch_PASA_pipeline.pl \
>         -c alignAssembly.config \
>         -R \
>         -g /media/TeraData/ipedroso/globus_endpoint/Ptrichocarpa_phytozome/v3.0/assembly/Ptrichocarpa_210_v3.0.fa \
>         -t /media/TeraData/ipedroso/globus_endpoint/Ptrichocarpa_phytozome/v3.0/annotation/Ptrichocarpa_210_v3.0.transcript.fa.clean \
>         -T \
>         -u /media/TeraData/ipedroso/globus_endpoint/Ptrichocarpa_phytozome/v3.0/annotation/Ptrichocarpa_210_v3.0.transcript.fa \
>         -f FL_accs.txt \
>         --ALIGNERS blat,gmap \
>         -L --annots_gff3 <(zcat /media/TeraData/ipedroso/globus_endpoint/Ptrichocarpa_phytozome/v3.0/annotation/Ptrichocarpa_210_v3.0.gene_exons.gff3.gz) \
>         --TDN ../trinity_de_novo/trinity_out_dir_run2/Trinity.fasta \
>         --ALT_SPLICE \
>         --CPU 20
>
>
> When I tried to re-started it says the database already exists. When
> modifying the options it complains that some of transcripts are already
> present on the database.
>
> [ipedroso@jimi PASA]$ $PASAHOME/scripts/Launch_PASA_pipeline.pl         -c alignAssembly.config         -R         -g /media/TeraData/ipedroso/globus_endpoint/Ptrichocarpa_phytozome/v3.0/assembly/Ptrichocarpa_210_v3.0.fa         -t /media/TeraData/ipedroso/globus_endpoint/Ptrichocarpa_phytozome/v3.0/annotation/Ptrichocarpa_210_v3.0.transcript.fa.clean         -T         -u /media/TeraData/ipedroso/globus_endpoint/Ptrichocarpa_phytozome/v3.0/annotation/Ptrichocarpa_210_v3.0.transcript.fa         -f FL_accs.txt         --ALIGNERS blat,gmap       --TDN ../trinity_de_novo/trinity_out_dir_run2/Trinity.fasta         --ALT_SPLICE         --CPU 20
>
>
> ## Processing CMD: 1/33
> 11:09:52        CMD: /home/ipedroso/APP/PASApipeline-2.0.1//scripts/upload_transcript_data.dbi -M Populus_trichocarpav3_2 -t /media/TeraData/ipedroso/globus_endpoint/Ptrichocarpa_phytozome/v3.0/annotation/Ptrichocarpa_210_v3.0.transcript.fa.clean -T ../trinity_de_novo/trinity_out_dir_run2/Trinity.fasta -f FL_accs.txt
> DBD::mysql::db do failed: Duplicate entry 'Potri.T155100.1' for key 'cdna_acc_idx' at /home/ipedroso/APP/PASApipeline-2.0.1//PerlLib//Mysql_connect.pm line 162, <$filehandle> line 1.
> failed query: < insert cdna_info (cdna_acc, is_assembly, is_fli, is_TDN, length, header) values (?,?,?,?,?,?) > values: Potri.T155100.1 0 1 0 830 Potri.T155100.1 pacid=26978278 locus=Potri.T155100 ID=Potri.T155100.1.v3.0 annot-version=v3.0
> Errors: Duplicate entry 'Potri.T155100.1' for key 'cdna_acc_idx'
>  at /home/ipedroso/APP/PASApipeline-2.0.1//PerlLib//Mysql_connect.pm line 173, <$filehandle> line 1.
>         Mysql_connect::RunMod('Mysql_connect=HASH(0x11f8a38)', ' insert cdna_info (cdna_acc, is_assembly, is_fli, is_TDN, len...', 'Potri.T155100.1', 0, 1, 0, 830, 'Potri.T155100.1 pacid=26978278 locus=Potri.T155100 ID=Potri.T...') called at /home/ipedroso/APP/PASApipeline-2.0.1//scripts/upload_transcript_data.dbi line 97
> Issuing rollback() due to DESTROY without explicit disconnect() of DBD::mysql::db handle Populus_trichocarpav3_2:localhost at /usr/share/perl5/vendor_perl/Carp.pm line 101.
>
>
> ERROR: The following command died with exit code (65280):
> /home/ipedroso/APP/PASApipeline-2.0.1//scripts/upload_transcript_data.dbi -M Populus_trichocarpav3_2 -t /media/TeraData/ipedroso/globus_endpoint/Ptrichocarpa_phytozome/v3.0/annotation/Ptrichocarpa_210_v3.0.transcript.fa.clean -T ../trinity_de_novo/trinity_out_dir_run2/Trinity.fasta -f FL_accs.txt
>
> Must re-run pipeline starting at index [1] via running Launch_PASA_pipeline with parameter '-s 1' (exclude param '-C' since db already created)
>
> [ipedroso@jimi PASA]$
>
>
>
>    -
>
>    What should I do when the previous run did not finished properly?
>    Should I delete the transcripts from the db?
>    -
>
>    Is there a way that the pipeline either re-writes data on the db or
>    simply detects it is there and carries on?
>
> Thanks in advance!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PASApipeline/PASApipeline/issues/6>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by inti** [comment]
Hi,
Ok, I see. That all makes more sense now. 
Thanks a lot

Inti
