### ISSUE TITLE
print date on screen log information

### ISSUE THREAD

**Issue by inti** [PASApipeline/PASApipeline#7]
Hi,
Would it be possible to print the date together with the time on the logs? for example

```
## Processing CMD:
21:05:30        CMD: /home/ipedroso/APP/PASApipeline-2.0.1//scripts/comprehensive_alt_splice_report.dbi -M Populus_trichocarpav3_2  > Populus_trichocarpav3_2.alt_splicing_supporting_evidence.txt
```

to look like 

```
## Processing CMD:
lun mar 23 10:17:05 CLST 2015        CMD: /home/ipedroso/APP/PASApipeline-2.0.1//scripts/comprehensive_alt_splice_report.dbi -M Populus_trichocarpav3_2  > Populus_trichocarpav3_2.alt_splicing_supporting_evidence.txt
```

It is useful to workout how long it took the whole pipeline when it runs overnight or for more than a day.

cheers,

Inti

**Comment by brianjohnhaas** [comment]
that should be easy enough

On Mon, Mar 23, 2015 at 9:15 AM, Inti Pedroso <notifications@github.com>
wrote:

> Hi,
> Would it be possible to print the date together with the time on the logs?
> for example
>
> ## Processing CMD:
> 21:05:30        CMD: /home/ipedroso/APP/PASApipeline-2.0.1//scripts/comprehensive_alt_splice_report.dbi -M Populus_trichocarpav3_2  > Populus_trichocarpav3_2.alt_splicing_supporting_evidence.txt
>
> to look like
>
> ## Processing CMD:
> lun mar 23 10:17:05 CLST 2015        CMD: /home/ipedroso/APP/PASApipeline-2.0.1//scripts/comprehensive_alt_splice_report.dbi -M Populus_trichocarpav3_2  > Populus_trichocarpav3_2.alt_splicing_supporting_evidence.txt
>
> It is useful to workout how long it took the whole pipeline when it runs
> overnight or for more than a day.
>
> cheers,
>
> Inti
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PASApipeline/PASApipeline/issues/7>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by inti** [comment]
cheers!
Inti

**Comment by brianjohnhaas** [comment]
done.   better late than never.
