### ISSUE TITLE
gmapl as extra aligner

### ISSUE THREAD

**Issue by colindaven** [PASApipeline/PASApipeline#8]
Dear all,

has anyone had trouble using the gmap version for large (I think > 4gb) genomes? In this case the binary "gmapl" should be used, but a different gmap index is also required.

I am about to hack the gmap command in the source code, but would it be worth integrating gmapl as an extra aligner option ?

Launch_PASA_pipeline.pl:# --ALIGNERS <string>   aligners (available options include: gmap, blat... can run both using 'gmap,blat')

Best wishes,
Colin

**Comment by brianjohnhaas** [comment]
Hi Colin,

I haven't tried that aligner yet.  If it'll generate gff3 alignments like
the regular gmap, then you can try using PASA's
 --IMPORT_CUSTOM_ALIGNMENTS_GFF3  option.

best,

~brian


On Wed, Mar 25, 2015 at 8:27 AM, colindaven <notifications@github.com>
wrote:

> Dear all,
>
> has anyone had trouble using the gmap version for large (I think > 4gb)
> genomes? In this case the binary "gmapl" should be used, but a different
> gmap index is also required.
>
> I am about to hack the gmap command in the source code, but would it be
> worth integrating gmapl as an extra aligner option ?
>
> Launch_PASA_pipeline.pl:# --ALIGNERS aligners (available options include:
> gmap, blat... can run both using 'gmap,blat')
>
> Best wishes,
> Colin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PASApipeline/PASApipeline/issues/8>.
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by colindaven** [comment]
Hi Brian,

thanks for your comment.

gmapl is actually supplied with gmap and seems to produce exactly the same very nicely constructed gff3 format output that gmap does.

I was able to circumvent the problem by making one change, "gmap" to "gmapl" in each of the following  PASA files:

scripts/GMAP_multifasta_processor.pl  
scripts/process_GMAP_alignments_gff3_chimeras_ok.pl

Then the rest of the PASA pipeline worked fine without any further changes.

Best wishes,
Colin

**Comment by brianjohnhaas** [comment]
Fantastic!  I'm glad it was that straightforward for you.

best,

~brian


On Fri, Mar 27, 2015 at 4:25 AM, colindaven <notifications@github.com>
wrote:

> Hi Brian,
>
> thanks for your comment.
>
> gmapl is actually supplied with gmap and seems to produce exactly the same
> very nicely constructed gff3 format output that gmap does.
>
> I was able to circumvent the problem by making one change, "gmap" to
> "gmapl" in each of the following PASA files:
>
> scripts/GMAP_multifasta_processor.pl
>
> scripts/process_GMAP_alignments_gff3_chimeras_ok.pl
>
> Then the rest of the PASA pipeline worked fine without any further changes.
>
> Best wishes,
> Colin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PASApipeline/PASApipeline/issues/8#issuecomment-86867131>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
