### ISSUE TITLE
Invoke GMAPL using the PASApipeline Docker instance

### ISSUE THREAD

**Issue by ejblom** [PASApipeline/PASApipeline#86]
Dear PASA-ers,

We get the following message:

"This is a large genome of more than 2^32 (4 billion) bp. You should run gmapl instead."

However, the option "--ALIGNER gmapl" is not working. Is there an additional switch required to get this to work? I do find the gmapl binary in the image, so it could work.

Best

EJ

**Comment by brianjohnhaas** [comment]
Hi EJ,

There's no direct support for gmapl here.  You can just hack the
/pasapipeline/scripts/process_GMAP_alignments_gff3_chimeras_ok.pl
script to integrate it.  Should be straightforward, maybe just changing
'gmap' to 'gampl' when the target genome is larger than gmap supports.

best,

~b

On Mon, Sep 24, 2018 at 8:57 AM ejblom <notifications@github.com> wrote:
>
> Dear PASA-ers,
>
> We get the following message:
>
> "This is a large genome of more than 2^32 (4 billion) bp. You should run
gmapl instead."
>
> However, the option "--ALIGNER gmapl" is not working. Is there an
additional switch required to get this to work? I do find the gmapl binary
in the image, so it could work.
>
> Best
>
> EJ
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas

**Comment by brianjohnhaas** [comment]
going to do this differently in a future release
